### ISSUE TITLE
KeyError in Stash

### ISSUE THREAD

**Issue by wentaozhu** [kakaobrain/torchgpipe#8] opened 2019-12-11 21:05 UTC
Thank you so much for the awesome repository!

I use stash and find there is an error in PoPCat().isolate(ns)

I have checked the stash is fine and have run successfully.

Thanks again for your help!

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torchgpipe/skip/skippable.py", line 173, in forward
    poppable_tensors[name] = skip_tracker.load(batch, ns, name)
  File "/opt/conda/lib/python3.6/site-packages/torchgpipe/skip/tracker.py", line 38, in load
    return self.tensors.pop((ns, name))
KeyError: (<Namespace 'bfb2fb79-66d2-4437-abf9-ef62cfb17836'>, 'k')
```

```
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torchgpipe/skip/skippable.py", line 175, in forward
    raise RuntimeError(f"'{name}' has not been stashed")
RuntimeError: 'k' has not been stashed
```

**Comment by wentaozhu** [comment] 2019-12-11 21:25
I find the name of (RuntimeError(f"'{name}' has not been stashed")) is changed randomly with 's', 'k', 'i', 'p'.

**Comment by sublee** [comment] 2019-12-11 21:37
Hi @wentaozhu, thanks for reporting a potential bug. As your second comment, I guess you specified a string at `stash=` or `pop=` like `stash='skip'`. Both options take multiple skip names rather than a single skip name. If my guess is correct, try `stash=['skip']` instead.

**Comment by wentaozhu** [comment] 2019-12-11 21:40
Yes. I forgot the []. Thank you so much!

**Comment by sublee** [comment] 2019-12-12 06:12
Actually, it would be better if an exception occurs at `stash`, not `pop`. I reopen this issue to make a better experience.

**Comment by wentaozhu** [comment] 2019-12-12 15:06
Thank you so much!

**Comment by sublee** [comment] 2019-12-13 00:37
@wentaozhu I could not reproduce your exception message. Here's my testing module:

```python
@skippable(stash='skip')                  
class Layer1(Layer):                      
    def forward(self, input):             
        yield stash('skip', input)        
        return input
                                          
@skippable(pop='skip')                    
class Layer2(Layer):                      
    def forward(self, input):             
        skip = yield pop('skip')          
        return input + skip
```

Here is the exception message and it is what I expected:

```
RuntimeError: 'skip' has not been declared as stashable
```

How did your module look like?

**Comment by wentaozhu** [comment] 2019-12-13 01:46
If you use
skippable(stash=［'skip'］)
and
skippable(pop='skip'),

You can reproduce the error. Thank you so much!

**Comment by sublee** [comment] 2019-12-13 09:25
@wentaozhu Thank you for making it reproducible. I got it. If you use `stash` and `pop` without `GPipe`, I highly recommend [`verify_skippables()`](https://torchgpipe.readthedocs.io/en/stable/api.html#torchgpipe.skip.verify_skippables) to check skip connection errors before training your module. You will get an exception like this before training:

```
TypeError: one or more pairs of stash and pop do not match:

* '1' declared 'p' as poppable but it was not stashed
* '1' declared 's' as poppable but it was not stashed
* '1' declared 'i' as poppable but it was not stashed
* '1' declared 'k' as poppable but it was not stashed
* no module declared 'skip' as poppable but stashed
```

I didn't find a point to improve. I close this issue.

**Closed by sublee** 2019-12-13 09:25 UTC
Labels: bug
